### ISSUE TITLE
Unable to locate package noderedrevpinodes-server

### ISSUE THREAD

**Issue by igusDroth** [erminas/noderedrevpinodes-server#1]

**Comment by crismancich** [comment]
It will be part of the RevPi image and it will be contained in the RevPi deb repository soon. Until then and if you need a local install, please use https://github.com/erminas/noderedrevpinodes-server.

**Comment by jgerlach-erminas** [comment]
@igusDroth Thanks for the feedback. The readme now also includes an alternative method to manually install the debian package from github.
