### ISSUE TITLE
Data delay in NodeRed dashboard on RevPi Core S

### ISSUE THREAD

**Issue by jgerlach-erminas** [erminas/noderedrevpinodes-server#12]
https://revolutionpi.de/forum/viewtopic.php?p=12976#p12975

User [KavenWong](https://revolutionpi.de/forum/memberlist.php?mode=viewprofile&u=1337) described a delay writing data to a dashboard using the Revpi Core S

**Comment by hbunjes** [comment]
Waiting for further input from user.
