### ISSUE TITLE
Input Names broken in the Dropdown

### ISSUE THREAD

**Issue by crismancich** [erminas/noderedrevpinodes-server#13]
Hi there,

I had a call from WESCO today. A customer had problems with NodeRed. In fact the dropdowns in 1.0.9 are showing a suffix.
So instead of I_1 we're seeting I_1_i03. And even if we change the value in pictory, it stays the same. Of course it does not work.
I'm about to investigate deeper. But maybe you already have an idea what may have caused this...

Cheers,
Boris

![screen_nodered](https://user-images.githubusercontent.com/7170343/200679059-063734bf-a740-4bcd-8cc2-ef047c4f90a8.png)

**Comment by hbunjes** [comment]
Those names are directly taken from the Config via RevPiModio. Can you provide the picture config please? I think we can dig deeper using this.

Thank you,
Hilmar

**Comment by crismancich** [comment]
I went back to the customer. They flashed a clean image again and used the version from the image without making a backup of the broken one. :( So I can't reproduce the issue.
If the problem reappears, I will get in touch.
