### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by anthrogan** [erminas/noderedrevpinodes-server#15]
Hi, 

I'm using a revpi with node-red but not in a traditional sense. Instead I'm using flowforge to deploy node-red instances to the device. While I'm editing a remote instance of node-red I can't list the pins due to default config disabling external users.

I'm struggling to understand where to put the `server_config.json` file? Does it need a folder in root creating or is there somewhere already made it needs to go?

Any guidance greatly appreciated.

**Comment by jgerlach-erminas** [comment]
Hello,
server configuration is described here : https://github.com/erminas/noderedrevpinodes-server/tree/master#configuration-optional If you have further questions, feel free to ask

**Comment by anthrogan** [comment]
The config doesn't appear to be working in that it won't allow external users. The config appears to load as it doesn't state anything about a default config. It states a broken config due to missing key, does external users need a private key generating? It's not really made clear in the documentation. 

The config I've used is:
```
{
    "version": "noderedrevpinodes-server_config_1.0.1",
    "port": 8000,
    "block_external_connections": false,
    "allow_all_user": true
}
```
![image](https://github.com/erminas/noderedrevpinodes-server/assets/30973884/fcaaf7ac-15e5-43ef-887a-122ef44956f1)

Also the server works fine, it emits the values based on tag name as expected, only the pin select drop down is not working.

As a work around I've ran a local instance of node-red and made a handful of nodes I'm interested in and exported them, I can then import these in to my cloud based flow fine. 
![image](https://github.com/erminas/noderedrevpinodes-server/assets/30973884/7c1d8417-ed96-4a4f-92bb-14277694740b)

To be absolutely clear I'm not sure how flowforge communicates with the flowforge agent on the device, I believe it runs the remote flow in a cloud instance and then pushes any changes to the end device, similarly it relays any debug messages back from the device to the cloud instance!

So its not game breaking but it's a bit of a difficulty using cloud based instances like flowforge and deploying to things like the RevPi.

Apologies if this is a bit of a convoluted issue, i appreciate the code is working as designed to be honest. I'm not great with python but if you point me in the right direction I'll look to make a PR for fix, I've written similar stuff with node OPCUA and S7 in the past 👍

**Comment by jgerlach-erminas** [comment]
Hello,
ok there are errors in the documentation and probably some problems with the handling of the configuration. Can you try the following configuration:
{
    "version": "noderedrevpinodes-server_config_1.0.1",
    "port": 8000,
    "block_external_connections": false,
    "allow_all_user": true,
    "private_key_file": "",
    "cert_file": ""
}

It should still give the warning: _Can't find valid certificate files, using self signed certificate instead!_ , but the external connections should work.

>It states a broken config due to missing key, does external users need a private key generating? 

No, a custom key is not required. The private_key_file and cert_file are meant to be optional, but this doesn't seem to be handled correctly.

In a future release we will fix the documentation and the optional parameter handling.
Thanks for your feedback,
Jonas

**Comment by hbunjes** [comment]
@anthrogan I just checked this issue. Is the log excerpt in the screenshot from the server where you cannot get the pin list? As the user is logged in the browser should be able to get the pin list as the user is not blocked. 

Can you post the websocket communication (from network tab in browser) and the complete server log? 

Also, what OS version is on the RevPi and is Pictory configured?

Thank you!

**Comment by anthrogan** [comment]
Yes that log is from the server (RevPi) however the browser isn't running on that same server its running using flowfuse (flowforge) which i think does some funky communication.

I'll get a full log/communication over to you asap 👍

**Comment by hbunjes** [comment]
Closing this after 6 month.
