### ISSUE TITLE
Error when installing: Release 'noderedrevpinodes-server_1_0_0.deb' for 'python2.7-talloc' was not found

### ISSUE THREAD

**Issue by ptskslv** [erminas/noderedrevpinodes-server#2]
I downloaded and installed the server as described at the Readme, but when installing, I've got some errors on the terminal. Am I missing some pre-installation steps?

I read a lot of `"Note, selecting 'libraries' for regex '.'"`, and then some
`"Release 'noderedrevpinodes-server_1_0_0.deb'` for 'python2.7-talloc' was not found"

Those two lines are examples, this happens with a lot of other packages/ libraries.

![error](https://user-images.githubusercontent.com/59292198/72097422-a515ed80-331c-11ea-83fe-23b5e6d90133.PNG)

Model: RevPiCore
PiCtory: 1.2.5
Year of Manufacturing: 2019

**Comment by crismancich** [comment]
Hi there,

thanks for your email. Could you please send us the results of the
following commands to jonas.gerlach@erminas.de?

uname -a
apt-get –version

This tells us about the versions you are using.

Greetings from Hamburg,
Boris Crismancich

ptskslv <notifications@github.com> schrieb am Do., 9. Jan. 2020, 20:18:

**Comment by nbuchwitz** [comment]
The problems seems to be in your setup command as apt-get tries to expand the dot in the path as an regular expression (first error). Try to quote the filename with single or double quotes.

**Comment by ptskslv** [comment]
Hello!

uname -a :  Linux RevPi12880 4.4.50-rt66+ #1 PREEMPT RT Wed, 20 Sep 2017
07:09:15 +0200 armv6l GNU/Linux

apt-get –version:
apt 1.0.9.8.5 for armhf compiled on Jan 22 2019 16:35:42
Supported modules:

*Ver: Standard .deb

*Pkg:  Debian dpkg interface (Priority 30)

Pkg:  Debian APT solver interface (Priority -1000)

S.L: 'deb' Standard Debian binary tree

S.L: 'deb-src' Standard Debian source tree

Idx: Debian Source Index

Idx: Debian Package Index

Idx: Debian Translation Index

Idx: Debian dpkg status file

Idx: EDSP scenario file


I also ran the commands:





*From here: https://revpimodio.org/quellen/quellen2/
<https://revpimodio.org/quellen/quellen2/>sudo apt-get updatesudo apt-get
install python3-revpimodio2sudo apt-get dist-upgrade and no success on
installing it afterwards.Thanks a lot for the support*


Am Do., 9. Jan. 2020 um 23:50 Uhr schrieb Boris Crismancich <
notifications@github.com>:

**Comment by ptskslv** [comment]
I ran:


`sudo dpkg -i ./noderedrevpinodes-server_1_0_0.deb                                                         

Selecting previously unselected package noderedrevpinodes-server.                                                           (Reading database ... 79760 files and directories currently installed.)                                                     Preparing to unpack .../noderedrevpinodes-server_1_0_0.deb ...                                                              Unpacking noderedrevpinodes-server (1.0.0) ...                                                                              dpkg: dependency problems prevent configuration of noderedrevpinodes-server:                                                 noderedrevpinodes-server depends on python3 (>= 3.5.3-1); however:                                                           Version of python3 on system is 3.4.2-2.                                                                                                                                                                                                              dpkg: error processing package noderedrevpinodes-server (--install):                                                         dependency problems - leaving unconfigured                                                                                 Errors were encountered while processing:                                                                                    noderedrevpinodes-server                   `


I guess I will update python3 and see what happens.

**Comment by jgerlach-erminas** [comment]
Hello,
it seems you're running the Raspbian Jessie Release image. Currently we are officially only supporting the newest [Raspbian Stretch image](https://revolution.kunbus.de/shop/en/stretch?___from_store=de). If it's possible, try updating your OS to Stretch, then you are also able to install the server directly via
sudo apt-get install noderedrevpinodes-server

**Comment by jgerlach-erminas** [comment]
Hi,
I'm closing the issue due to inactivity. If you still experience this issue, feel free to open a new thread.
