### ISSUE TITLE
Don't write logfile to /usr/share/...

### ISSUE THREAD

**Issue by iluminat23** [erminas/noderedrevpinodes-server#6]
The log file is currently written to `/usr/share/noderedrevpinodes-server/`.  This directory might be read-only. Or should not be written to avoid wear out of the flash memory. A directory below `/var/` most likely `/var/log/` would be appropriate.

**Comment by iluminat23** [comment]
https://github.com/erminas/noderedrevpinodes-server/pull/7

**Comment by dfilsinger-erminas** [comment]
was changed with release 1.0.3
