### ISSUE TITLE
Node RED WS server connection randomly disconnects and connects back

### ISSUE THREAD

**Issue by kb-jadhav** [erminas/noderedrevpinodes-server#9]
Connection to Node RED WS server is randomly interrupted and noticed with inject node repeat interval (eg: 3s or even higher) and when many revpi nodes are used.

**Observed in RevPi Buster Image**: 

pi@RevPi40618:~ $ dpkg -l | grep nodeii  nodejs                               12.22.1-1nodesource1                armhf        Node.js event-based server-side javascript engineii  **noderedrevpinodes-server             1.0.2-2**                             all          Server backend for the RevPi-NodeRed-Nodes

**node-red-contrib-revpi-nodes 1.0.7-2**

As sample example “**RevPiVirtualNodeRED Example**“ 

Reads Virtual Inputs (Input_1 to Input_32) and Writes to Virtual Outputs (Output_1 to Output_32) the values as 
Output Pin Value = input Pin Val + Input pin index no
where Pin index can be 0...31

_Pictory configuration: Revpi Connect and Virtual Device 32 Byte as default._

![image](https://user-images.githubusercontent.com/72547941/122772735-f6633400-d2a7-11eb-9543-653ced42aed7.png)

_RevPiVirtualNodeRED Example flow when connected_

![image](https://user-images.githubusercontent.com/72547941/122772893-1eeb2e00-d2a8-11eb-97f0-b638b7ba357c.png)

_RevPiVirtualNodeRED Example flow when disconnected_

![nodes disconnected](https://user-images.githubusercontent.com/72547941/122773064-48a45500-d2a8-11eb-8280-7286f775cb82.png)

**node-red-log**

pi@RevPi40618:~ $ node-red-log

Lost connection to WS Server!
Try to reconnect - Attempt: 1
Connecting to WS Server wss://127.0.0.1:8000
Connection to WS Server established!
info Authorized by server!
Lost connection to WS Server!
Try to reconnect - Attempt: 1
Connecting to WS Server wss://127.0.0.1:8000
Connection to WS Server established!
info Authorized by server!
Lost connection to WS Server!
Try to reconnect - Attempt: 1
Connecting to WS Server wss://127.0.0.1:8000
Connection to WS Server established!
info Authorized by server!
Lost connection to WS Server!
Try to reconnect - Attempt: 1
Connecting to WS Server wss://127.0.0.1:8000
Connection to WS Server established!
info Authorized by server!
Lost connection to WS Server!
Try to reconnect - Attempt: 1
Connecting to WS Server wss://127.0.0.1:8000
Connection to WS Server established!
info Authorized by server!

**Attachment:** RevPiVirtualNodeRED.zip Example flow **RevPiVirtualNodeRED.json**
[RevPiVirtualNodeRED.zip](https://github.com/erminas/noderedrevpinodes-server/files/6687107/RevPiVirtualNodeRED.zip)

This can also be observed when revpi-getpin node is called many times (approx 5 or more) in a flow.

**Comment by thack-enit** [comment]
@crismancich I had the same problem and eventually found out it was an error on the NodeRED side. Sometimes the flow produced an `undefined` payload. When this is fed into a `revpi-output` Node this caused the same error you also had.  Although arguably this should not lead to a de-facto crash of the server but should be caught and with a corresponding error message returned to the caller.

**Comment by nbuchwitz** [comment]
@kb-jadhav I tested this with the latest server (https://github.com/erminas/noderedrevpinodes-server/tree/bugfix_send_only_after_receive) and nodes (https://github.com/erminas/node-red-contrib-revpi-nodes/tree/release_1.0.9) and it seems to work now.

[flows.zip](https://github.com/erminas/noderedrevpinodes-server/files/8324014/flows.zip)

**Comment by dfilsinger-erminas** [comment]
Hey,
I also tested it with the latest versions ([Server 1.0.4](https://github.com/erminas/noderedrevpinodes-server/releases/tag/1.0.4)  / [Nodes 1.0.9](https://github.com/erminas/node-red-contrib-revpi-nodes/releases/tag/1.0.9)) and could not reproduce it.
As Nicolai said, it seems to work now.
